#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#Change location for your wallpaper. Feh is redundant but eh
feh --bg-fill $HOME/Pictures/Virginia.jpg &
wal -i $HOME/Pictures/Virginia.jpg &
polybar &
xss-lock -- betterlockscreen -l &
picom &
setxkbmap -option "caps:super" &
dunst &

#Colors 
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
